### ISSUE TITLE
use either `data` or `inst` to distribute data with an R package

### ISSUE THREAD

**Issue by cmatKhan** [westbrooktm/GOeval#16]
There are two standard ways of distributing data along with an R package -- you can place a file like what you have in `vignettes/data` in a directory in the top level of the package called `inst`. 

As reference for using `inst/`, [see here](https://r-pkgs.org/misc.html#sec-misc-inst)

If you use `inst/`, your line in the Get Started vignette:

```
data_path <- system.file(package = "GOeval", file.path("data", "vignette_data.tar.gz"))

# wherever you want to store the example data
data_dir <- "GOeval_data"

untar(data_path, exdir = data_dir)
```

would look like this:

```
data_path <- system.file(package = "GOeval", file.path("vignette_data.tar.gz"))
```

Another way of distributing data with a package is in the `data` directory. In this case, the data is stored as an R object and is read into memory when the package is loaded. This is a pretty common way for packages to distribute 'test' or 'minimal demonstration' type data and appropriate as long as the data isn't too big (it could slow down the load time of your package for your user then). Best way or doing this is to use `usethis::use_data(<data_object_name>)`. [See here](https://r-pkgs.org/data.html#sec-data-data)

**Comment by westbrooktm** [comment]
As of 1.0.0, the vignette data is in `inst/`.
