### ISSUE TITLE
Check input at the top of every function

### ISSUE THREAD

**Issue by cmatKhan** [westbrooktm/GOeval#18]
A very standard, and very good, software design principle is that code should "fail fast", meaning that if something is wrong, it should be caught as quickly as possible. The error message that results from a failure such as this should be easy to understand (as you know, base R error messages are cryptic and unhelpful at best, usually).

As a specific example, rather than the [input format as a detail](https://github.com/westbrooktm/GOeval/blob/3f20b1cb7c1dfff539564fc0f7aecda98bbee76e/R/evaluate.R#L47), require it with something like:

```R
stopifnot(length(setdiff(colnames(input_df), c('required_col1', 'required_col2', 'required_col3')) == 0)
```
You could also use [assertthat](https://github.com/hadley/assertthat). To make a more readable error message (probably a good idea in this case), just expand the `stopifnot` into a conditional:

```R
if (!<input_condition>){
  stop('message to your user about how their input doesn't conform')
}
```

other examples are things like, when `output_dir` is an input variable, you should check that the path exists.

As an aside, if someone were to use this package in their own software, then they could catch any of these errors with a `tryCatch` phrase.

**Comment by westbrooktm** [comment]
Functions now stop at the beginning if the input is not in the correct format.
